### ISSUE TITLE
linkcleaner.js Mistype

### ISSUE THREAD

**Issue by MichelePezza** [Lucknell/Firefox_Link_Cleaner#1]
Mistype in line 142  - var repalce = "" - maybe the it is - var  replace = ""  -

ciao
Michele

**Comment by Lucknell** [comment]
Thanks for for catching that! I didn't notice I added the space in there! I will try to push that change here and to the extension some time this week.

**Comment by Lucknell** [comment]
Misread the issue a when I first commented. Typo is fixed in newest commit thank you again for the review
